python main.py --dataset cifar10 --seed 0
python main.py --dataset cifar10 --seed 1
python main.py --dataset cifar10 --seed 2
python main.py --dataset cifar100 --seed 0
python main.py --dataset cifar100 --seed 1
python main.py --dataset cifar100 --seed 2
python main.py --dataset tiny-imagenet --seed 0
python main.py --dataset tiny-imagenet --seed 1
python main.py --dataset tiny-imagenet --seed 2
