cifar10:
    eps: 8
    tau: 0.9995
    ls: 0.6
    lambda: 100
    min_mask_ratio: 0.1
    max_mask_ratio: 0.5
    train_size: 49000
    batch_size: 128
    num_workers: 4
    epochs: 100
    class_num: 10
    lr: 0.1
    max_lr: 0.1
    device: 'cuda:0'
    log_path: './logs/cifar10'
    image_size: 32
    li_update: 20

cifar100:
    eps: 8
    tau: 0.9995
    ls: 0.8
    lambda: 200
    min_mask_ratio: 0.1
    max_mask_ratio: 0.5
    train_size: 49000
    batch_size: 128
    num_workers: 4
    epochs: 100
    class_num: 100
    lr: 0.1
    max_lr: 0.1
    device: 'cuda:0'
    log_path: './logs/cifar100'
    image_size: 32
    li_update: 20

tiny-imagenet:
    eps: 8
    tau: 0.9995
    ls: 0.6
    lambda: 100
    min_mask_ratio: 0.1
    max_mask_ratio: 0.5
    train_size: 98000
    batch_size: 128
    num_workers: 4
    epochs: 100
    class_num: 200
    lr: 0.1
    max_lr: 0.1
    device: 'cuda:0'
    log_path: './logs/tiny-imagenet'
    image_size: 64
    li_update: 20

cifar10-eps16:
    eps: 16
    tau: 0.9995
    ls: 0.4
    lambda: 20
    min_mask_ratio: 0.0
    max_mask_ratio: 1.0
    train_size: 49000
    batch_size: 128
    num_workers: 4
    epochs: 100
    class_num: 10
    lr: 0.1
    max_lr: 0.1
    device: 'cuda:0'
    log_path: './logs/cifar10_eps16'
    image_size: 32
    li_update: 10

cifar100-eps16:
    eps: 16
    tau: 0.9995
    ls: 0.4
    lambda: 20
    min_mask_ratio: 0.0
    max_mask_ratio: 1.0
    train_size: 49000
    batch_size: 128
    num_workers: 4
    epochs: 100
    class_num: 100
    lr: 0.1
    max_lr: 0.1
    device: 'cuda:0'
    log_path: './logs/cifar100_eps16'
    image_size: 32
    li_update: 20

tiny-imagenet-eps12:
    eps: 12
    tau: 0.9995
    ls: 0.4
    lambda: 20
    min_mask_ratio: 0.0
    max_mask_ratio: 1.0
    train_size: 98000
    batch_size: 128
    num_workers: 4
    epochs: 100
    class_num: 200
    lr: 0.1
    max_lr: 0.1
    device: 'cuda:0'
    log_path: './logs/tiny-imagenet_eps12'
    image_size: 64
    li_update: 20